"""Generators for synthetic demo/test fixtures containing safe example metadata."""

from __future__ import annotations

import io
from pathlib import Path

from PIL import Image

from ghostmark.formats import jpeg, png

# Minimal, valid, empty little-endian TIFF structure: header + zero-entry IFD.
# Used as placeholder EXIF payload data. It is intentionally content-free.
_MINIMAL_TIFF = b"II*\x00" + (8).to_bytes(4, "little") + (0).to_bytes(2, "little") + (0).to_bytes(4, "little")

_DEMO_XMP = b"""<?xpacket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
   <dc:creator>GhostMark Demo Fixture</dc:creator>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"""


def demo_text() -> str:
    """Multilingual text containing safe-to-detect hidden Unicode signals."""

    zwsp = chr(0x200B)  # ZERO WIDTH SPACE
    word_joiner = chr(0x2060)  # WORD JOINER
    tag_chars = "".join(chr(0xE0000 + ord(c)) for c in "ghostmark" if 0x20 <= ord(c) <= 0x7E)

    return (
        "GhostMark demo fixture.\n\n"
        f"English: This{zwsp} text{zwsp} contains{word_joiner} hidden characters.\n"
        "French: J'aime l'intelligence artificielle. Ça fonctionne très bien.\n"
        "German: Übermäßige Änderungen dürfen den Text nicht beschädigen.\n"
        "Emoji: 👻 🔍 ✅\n"
        f"Hidden tag block: {tag_chars}\n"
        "```python\nprint('code blocks are preserved')\n```\n"
    )


def make_jpeg_fixture(path: Path) -> None:
    """A small JPEG with synthetic EXIF, XMP, IPTC and comment segments."""

    base = Image.new("RGB", (64, 64), color=(120, 160, 200))
    buf = io.BytesIO()
    base.save(buf, format="JPEG", quality=90)
    data = buf.getvalue()

    segments, rest = jpeg.parse_header_segments(data)
    sos = segments[-1]
    header_segments = segments[:-1]

    exif_payload = jpeg.EXIF_PREFIX + _MINIMAL_TIFF
    xmp_payload = jpeg.XMP_PREFIX + _DEMO_XMP
    iptc_payload = jpeg.PHOTOSHOP_PREFIX + b"\x1c\x02\x0f\x00\x03GhostMark Demo"
    comment_payload = b"Generated by GhostMark demo fixtures. Not real camera output."

    new_segments = [
        *header_segments,
        jpeg.Segment(marker=jpeg.APP1, payload=exif_payload),
        jpeg.Segment(marker=jpeg.APP1, payload=xmp_payload),
        jpeg.Segment(marker=jpeg.APP13, payload=iptc_payload),
        jpeg.Segment(marker=jpeg.COM, payload=comment_payload),
        sos,
    ]
    path.write_bytes(jpeg.rebuild(new_segments, rest))


def make_png_fixture(path: Path) -> None:
    """A small PNG with synthetic text metadata, XMP and an eXIf chunk."""

    base = Image.new("RGB", (64, 64), color=(200, 140, 120))
    buf = io.BytesIO()
    base.save(buf, format="PNG")
    data = buf.getvalue()

    chunks = png.parse_chunks(data)
    iend_index = next(i for i, c in enumerate(chunks) if c.type == b"IEND")

    text_chunk = png.Chunk(type=b"tEXt", data=b"Comment\x00Generated by GhostMark demo fixtures")
    xmp_chunk = png.Chunk(type=b"iTXt", data=b"XML:com.adobe.xmp\x00\x00\x00\x00\x00" + _DEMO_XMP)
    exif_chunk = png.Chunk(type=b"eXIf", data=_MINIMAL_TIFF)

    new_chunks = chunks[:iend_index] + [text_chunk, xmp_chunk, exif_chunk] + chunks[iend_index:]
    path.write_bytes(png.rebuild(new_chunks))


def make_pdf_fixture(path: Path) -> None:
    """A small single-page PDF with DocInfo and XMP metadata."""

    import pikepdf

    pdf = pikepdf.new()
    pdf.add_blank_page(page_size=(200, 200))
    with pdf.open_metadata() as meta:
        meta["dc:title"] = "GhostMark Demo Fixture"
        meta["dc:creator"] = ["GhostMark demo fixtures"]
        meta["xmp:CreatorTool"] = "GhostMark demo generator"
    pdf.docinfo["/Title"] = "GhostMark Demo Fixture"
    pdf.docinfo["/Author"] = "GhostMark demo fixtures"
    pdf.docinfo["/Producer"] = "GhostMark"
    pdf.save(str(path))
    pdf.close()


def generate_all(directory: Path) -> dict[str, Path]:
    directory.mkdir(parents=True, exist_ok=True)
    paths = {
        "text": directory / "demo.txt",
        "jpeg": directory / "demo.jpg",
        "png": directory / "demo.png",
        "pdf": directory / "demo.pdf",
    }
    paths["text"].write_text(demo_text(), encoding="utf-8")
    make_jpeg_fixture(paths["jpeg"])
    make_png_fixture(paths["png"])
    make_pdf_fixture(paths["pdf"])
    return paths
