"""End-to-end verification against the REAL c2patool binary.

Fixtures generated by GhostMark never contain a C2PA manifest, so this
suite's job is narrower than the ExifTool one: it confirms that GhostMark
can actually find and run a real c2patool install, that a manifest-free
fixture is correctly reported as "no manifest found" (not a false
positive, not a guess), and that the full verification pipeline includes
c2patool's outcome without letting it block VERIFIED CLEAN on its own.

Skips (does not fail) when c2patool isn't installed, so local `pytest`
runs are unaffected. CI's independent-verification job installs c2patool
via `cargo install` and this suite MUST pass there -- see
.github/workflows/ci.yml.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from ghostmark.cleaner import clean_file
from ghostmark.fixtures.generate import make_jpeg_fixture, make_pdf_fixture, make_png_fixture
from ghostmark.independent_verify import C2paToolVerifier
from ghostmark.verifier import verify_file

verifier = C2paToolVerifier()

pytestmark = pytest.mark.skipif(
    not verifier.available(),
    reason="c2patool is not installed locally; this suite runs in CI's independent-verification job.",
)


@pytest.mark.parametrize(
    ("make_fixture", "filename"),
    [
        (make_pdf_fixture, "demo.pdf"),
        (make_jpeg_fixture, "demo.jpg"),
        (make_png_fixture, "demo.png"),
    ],
)
def test_real_c2patool_reports_no_manifest_on_plain_fixture(tmp_path: Path, make_fixture, filename):
    path = tmp_path / filename
    make_fixture(path)

    result = verifier.inspect(path)

    assert result.available is True
    assert result.applicable is True
    assert result.found is False, (
        f"c2patool reported a manifest on a fixture that never had one: {result.note}"
    )


def test_real_c2patool_version_is_reported():
    version = verifier.version()
    assert version is not None
    assert version[0].isdigit()


def test_full_verification_pipeline_includes_c2patool_without_blocking_verified_clean():
    """c2patool agreeing (no manifest, none expected) must not prevent VERIFIED CLEAN."""

    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "demo.jpg"
        make_jpeg_fixture(path)
        clean_result = clean_file(path)
        cleaned_path = Path(clean_result.output)

        result = verify_file(path, cleaned_path)

        assert result.c2pa_after is not None
        assert result.c2pa_after.available is True
        assert result.c2pa_after.found is False
        assert result.summary_v2 is not None
        assert result.summary_v2.verdict.value == "verified_clean"
