"""GhostMark's public, reproducible, synthetic test corpus.

Lives inside the installed package (``src/ghostmark/corpus/``) rather than
under ``tests/`` so it ships with every install mode -- editable dev
install, a built wheel, and the production Docker image (which only
copies ``src/``) -- and so the public ``/benchmarks`` page can read the
exact same fixtures the regression suite (``tests/test_corpus.py``) runs
against. There is nothing copyrighted or private here; every fixture is
generated by ``ghostmark.fixtures.generate`` (see ``scripts/generate_corpus.py``).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

CORPUS_DIR = Path(__file__).parent / "corpus"
MANIFEST_PATH = CORPUS_DIR / "manifest.json"


def load_manifest() -> list[dict[str, Any]]:
    data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    return data["fixtures"]


def fixture_path(entry: dict[str, Any]) -> Path:
    return CORPUS_DIR / entry["path"]
